# Pull the base image with python 3.8 as a runtime for your Lambda
FROM public.ecr.aws/lambda/nodejs:18

RUN yum update -y && yum install -y python3
# Copy the earlier created requirements.txt file to the container
COPY requirements.txt ./

# Install the python requirements from requirements.txt
RUN python3 -m pip install -r requirements.txt
# Replace Pillow with Pillow-SIMD to take advantage of AVX2

# Copy the earlier created app.py file to the containerworkspace/aws-lambda-wasm-runtime/api/Dockerfile
COPY app.py ./
COPY labels_mobilenet_quant_v1_224.txt ./
COPY mobilenet_v1_1.0_224_quant.tflite ./

# Set the CMD to your handler
COPY *.js ./

CMD [ "hello.handler" ]